// This file is auto-generated by @hey-api/openapi-ts

/**
 * AuthUserSchema
 */
export type AuthUserSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * CsrfAuthUserSchema
 */
export type CsrfAuthUserSchema = {
    /**
     * Csrftoken
     */
    csrfToken: string;
    authUser: AuthUserSchema;
};

/**
 * ErrorMessage
 */
export type ErrorMessage =
    | "User is unauthenticated."
    | "Invalid auth token."
    | "Resource does not exist.";

/**
 * ErrorSchema
 */
export type ErrorSchema = {
    detail: ErrorMessage;
};

export type CheckLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/auth/login";
};

export type CheckLoginErrors = {
    /**
     * Unauthorized
     */
    401: ErrorSchema;
};

export type CheckLoginError = CheckLoginErrors[keyof CheckLoginErrors];

export type CheckLoginResponses = {
    /**
     * OK
     */
    200: CsrfAuthUserSchema;
};

export type CheckLoginResponse = CheckLoginResponses[keyof CheckLoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/auth/logout";
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};
