# Generated by Django 5.2.2 on 2025-06-14 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_chats", "0002_historicalmessage_llm_message_llm_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION public.threaded_messages(message_id uuid, max_characters integer)
 RETURNS TABLE(id uuid, created timestamp with time zone, modified timestamp with time zone, title text, content text, author_id uuid, conversation_id uuid, reply_to_id uuid, llm text)
 LANGUAGE sql
 STABLE
AS $function$
WITH RECURSIVE context_chain AS (
	-- Start with the initial message
	SELECT
		id,
		created,
		modified,
		title,
		content,
		author_id,
		conversation_id,
		reply_to_id,
		llm,
		length(content) AS total_length
	FROM
		message
	WHERE
		id = message_id
	UNION ALL
	-- Recursively fetch previous messages, stopping when total_length exceeds max_characters
	SELECT
		m.id,
		m.created,
		m.modified,
		m.title,
		m.content,
		m.author_id,
		m.conversation_id,
		m.reply_to_id,
	    m.llm,
		c.total_length + length(m.content)
	FROM
		message m
		JOIN context_chain c ON m.id = c.reply_to_id
	WHERE
		c.total_length + length(m.content) <= max_characters
)
SELECT
	id,
	created,
	modified,
	title,
	content,
	author_id,
	conversation_id,
	reply_to_id,
	llm
FROM
	context_chain;
$function$
;
            """,
            reverse_sql="""
DROP FUNCTION public.threaded_messages;
            """,
        )
    ]
