# Generated by Django 5.2.2 on 2025-06-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_chats", "0003_auto_20250614_0534"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="message_branches",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalconversation",
            name="message_branches",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalmessage",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("utils-echo", "UTILS_ECHO"),
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmessage",
            name="title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("utils-echo", "UTILS_ECHO"),
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
