# Generated by Django 5.2.2 on 2025-06-15 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_chats", "0005_historicalsetting_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsetting",
            name="llms_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="llms_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
