# Generated by Django 5.2.2 on 2025-06-15 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_chats", "0006_historicalsetting_llms_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsetting",
            name="llms_selected",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="llms_selected",
        ),
    ]
