# Generated by Django 5.2.2 on 2025-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_chats", "0012_remove_conversation_db_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="message_branches",
        ),
        migrations.RemoveField(
            model_name="historicalconversation",
            name="message_branches",
        ),
        migrations.AddField(
            model_name="conversationmember",
            name="message_branches",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalconversationmember",
            name="message_branches",
            field=models.JSONField(default=dict),
        ),
    ]
