# Generated by Django 5.2.2 on 2025-06-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmessage",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
