# Generated by Django 5.2.2 on 2025-06-15 06:04

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_conversation_message_branches_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("llm_nickname", models.TextField(default="")),
                ("llm_job", models.TextField(default="")),
                (
                    "llm_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("llm_context", models.TextField(default="")),
                (
                    "llms_selected",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("utils-echo", "UTILS_ECHO"),
                                ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                                ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                                ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical setting",
                "verbose_name_plural": "historical settings",
                "db_table": "setting_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("llm_nickname", models.TextField(default="")),
                ("llm_job", models.TextField(default="")),
                (
                    "llm_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("llm_context", models.TextField(default="")),
                (
                    "llms_selected",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("utils-echo", "UTILS_ECHO"),
                                ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                                ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                                ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "setting",
            },
        ),
    ]
