# Generated by Django 5.2.2 on 2025-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0007_remove_historicalsetting_llms_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme_background_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme_border_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme_primary_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme_secondary_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_theme_text_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme_background_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme_border_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme_primary_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme_secondary_override",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_theme_text_override",
            field=models.TextField(default=""),
        ),
    ]
