# Generated by Django 5.2.2 on 2025-06-15 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0008_historicalsetting_visual_theme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsetting",
            name="llm_context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="llm_job",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="llm_nickname",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="llm_traits",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme_background_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme_border_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme_primary_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme_secondary_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="visual_theme_text_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="llm_context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="llm_job",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="llm_nickname",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="llm_traits",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme_background_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme_border_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme_primary_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme_secondary_override",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="setting",
            name="visual_theme_text_override",
            field=models.TextField(blank=True, default=""),
        ),
    ]
