# Generated by Django 5.2.2 on 2025-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0010_conversationmember_llms_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmember",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalconversationmember",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
