# Generated by Django 5.2.2 on 2025-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0013_remove_conversation_message_branches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_branch_vertical",
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_branch_vertical",
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="conversationmember",
            name="message_branches",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalconversationmember",
            name="message_branches",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
