# Generated by Django 5.2.2 on 2025-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0015_historicalmessage_llm_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsetting",
            name="visual_stats_for_nerds",
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="setting",
            name="visual_stats_for_nerds",
            field=models.TextField(blank=True, default=False),
        ),
    ]
