# Generated by Django 5.2.2 on 2025-06-18 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0016_historicalsetting_visual_stats_for_nerds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmember",
            name="llms_selected",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                        ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                        ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                        ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                        ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                        ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalconversationmember",
            name="llms_selected",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                        ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                        ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                        ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                        ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                        ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmessage",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("utils-echo", "UTILS_ECHO"),
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                    ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                    ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                    ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                    ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                    ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsetting",
            name="llms_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                        ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                        ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                        ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                        ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                        ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="llm",
            field=models.TextField(
                blank=True,
                choices=[
                    ("utils-echo", "UTILS_ECHO"),
                    ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                    ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                    ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                    ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                    ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                    ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                    ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                    ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="llms_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("utils-echo", "UTILS_ECHO"),
                        ("openai-gpt-4.1", "OPENAI_GPT_4_1"),
                        ("openai-gpt-4.1-mini", "OPENAI_GPT_4_1_MINI"),
                        ("openai-gpt-4.1-nano", "OPENAI_GPT_4_1_NANO"),
                        ("gemini-2.0-flash", "GEMINI_2_0_FLASH"),
                        ("gemini-2.0-flash-lite", "GEMINI_2_0_FLASH_LITE"),
                        ("gemini-2.5-pro", "GENIMI_2_5_PRO"),
                        ("gemini-2.5-flash", "GENIMI_2_5_FLASH"),
                        ("gemini-2.5-flash-lite", "GENIMI_2_5_FLASH_LITE"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
