# Generated by Django 5.2.2 on 2025-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="username",
            field=models.TextField(db_index=True, default="fletcheaston"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.TextField(default="fletcheaston", unique=True),
            preserve_default=False,
        ),
    ]
