# Generated by Django 5.2.2 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0003_conversation_conversationmember_conversationtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="image_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.TextField(default=""),
        ),
    ]
